/* Generated by scripts/build-product-config.mjs. Public values only; no secrets. */
window.FIT_TIMER_CONFIG = Object.freeze({
  "id": "ru.fittimer.app",
  "name": "Fit Timer",
  "slug": "fit-timer",
  "brand": {
    "background": "#0C0916",
    "notificationAccent": "#7047EB"
  },
  "features": {
    "profiles": true,
    "premium": true,
    "ai": true,
    "notifications": true,
    "biometrics": true,
    "sharing": true
  },
  "apiBase": "",
  "publicAppUrl": ""
});
