/* Generated by scripts/build-product-config.mjs. Public values only; no secrets. */
window.FIT_TIMER_CONFIG = Object.freeze({
  "appId": "ru.fittimer.app",
  "appName": "Fit Timer",
  "slug": "fit-timer",
  "brand": {
    "background": "#0C0916",
    "notificationAccent": "#7047EB",
    "ui": {
      "dark": {
        "background": "#0C0916",
        "card": "#171126",
        "surface": "#1F1733",
        "accent": "#7C56F5",
        "accentInk": "#B7A0FF"
      },
      "light": {
        "background": "#F6F4FC",
        "card": "#FFFFFF",
        "surface": "#F2EEFC",
        "accent": "#6B3FE0",
        "accentInk": "#5A2ECB"
      }
    }
  },
  "features": {
    "profiles": true,
    "premium": true,
    "ai": true,
    "notifications": true,
    "biometrics": true,
    "sharing": true
  },
  "apiBase": "",
  "publicAppUrl": ""
});
