import { readFile, writeFile } from 'node:fs/promises';
import ts from 'typescript';

const CHECK = process.argv.includes('--check');
// This deterministic concatenation is also the CI consistency gate for generated sources.

const targets = [
  {
    target: 'app.js',
    parts: [
      'src/app/00-dependencies.js',
      'src/app/00-core.js',
      'src/app/10-data-sync.js',
      'src/app/20-account.js',
      'src/app/30-progress-media.js',
      'src/app/40-programs-ai.js',
      'src/app/50-trainer-catalog.js',
      'src/app/60-builder.js',
      'src/app/70-workout.js',
      'src/app/80-platform.js',
      'src/app/90-events.js'
    ]
  },
  {
    target: 'style.css',
    parts: [
      'src/styles/00-foundation.css',
      'src/styles/10-start-workout.css',
      'src/styles/20-finish.css',
      'src/styles/30-themes-settings.css',
      'src/styles/40-home.css',
      'src/styles/50-components-trainer.css',
      'src/styles/60-progress.css'
    ]
  },
  {
    target: 'index.html',
    parts: [
      'src/html/00-shell-home.html',
      'src/html/10-programs-builder.html',
      'src/html/20-workout-finish.html',
      'src/html/30-onboarding-account.html',
      'src/html/40-profiles.html',
      'src/html/50-profile-progress.html'
    ]
  }
];


/* app.js is an ES module, so its top-level names are no longer globals. Browser tests
   still inspect and stub product internals the way they did when app.js was a classic
   script. This generated bridge re-exposes every top-level binding on globalThis, but
   only when the test harness sets globalThis.__FIT_TEST_MODE__ (never in production).
   Mutable bindings (let/var/function) get setters so test stubs keep replacing them;
   imported bindings (e.g. the i18n API) are exposed read-only. */
function testBridge(source){
  const file = ts.createSourceFile('app.js', source, ts.ScriptTarget.ES2022, false, ts.ScriptKind.JS);
  const names = new Map();
  const add = (name, mutable) => { if(name && !names.has(name)) names.set(name, mutable); };
  const bindingNames = node => {
    if(ts.isIdentifier(node)) return [node.text];
    return node.elements.flatMap(el => ts.isOmittedExpression(el) ? [] : bindingNames(el.name));
  };
  for(const stmt of file.statements){
    if(ts.isFunctionDeclaration(stmt) && stmt.name) add(stmt.name.text, true);
    else if(ts.isClassDeclaration(stmt) && stmt.name) add(stmt.name.text, false);
    else if(ts.isImportDeclaration(stmt) && stmt.importClause){
      const clause = stmt.importClause;
      if(clause.name) add(clause.name.text, false);
      const bindings = clause.namedBindings;
      if(bindings && ts.isNamedImports(bindings)) for(const el of bindings.elements) add(el.name.text, false);
    }
    else if(ts.isVariableStatement(stmt)){
      const mutable = !(stmt.declarationList.flags & ts.NodeFlags.Const);
      for(const decl of stmt.declarationList.declarations) for(const name of bindingNames(decl.name)) add(name, mutable);
    }
  }
  const lines = [...names].map(([name, mutable]) => mutable
    ? `  __fitExpose(${JSON.stringify(name)}, () => ${name}, value => { ${name} = value; });`
    : `  __fitExpose(${JSON.stringify(name)}, () => ${name});`);
  return `
/* Generated by scripts/build-sources.mjs — test-only binding bridge, inert in production. */
if(globalThis.__FIT_TEST_MODE__ === true){
  const __fitExpose = (name, get, set) => {
    const current = Object.getOwnPropertyDescriptor(globalThis, name);
    if(current && !current.configurable) return;
    Object.defineProperty(globalThis, name, set ? {configurable:true, get, set} : {configurable:true, get});
  };
${lines.join('\n')}
}
`;
}

let bad = false;
for (const item of targets) {
  const chunks = await Promise.all(item.parts.map(path => readFile(path, 'utf8')));
  const joined = chunks.join('');
  const next = item.target === 'app.js' ? joined + testBridge(joined) : joined;
  if (CHECK) {
    const current = await readFile(item.target, 'utf8');
    if (current !== next) {
      bad = true;
      console.error(`${item.target} is stale. Run: npm run build:sources`);
    } else {
      console.log(`${item.target}: source parts are in sync`);
    }
  } else {
    const current = await readFile(item.target, 'utf8').catch(() => '');
    if (current !== next) {
      await writeFile(item.target, next, 'utf8');
      console.log(`rebuilt ${item.target}`);
    } else {
      console.log(`${item.target}: unchanged`);
    }
  }
}
if (bad) process.exit(1);
