/* Test-only binding bridge for the product runtime modules (src/app/NN-*.js,
   src/app/00-dependencies.js, src/i18n/index.js).

   Browser tests inspect and stub product internals by name on globalThis, the way they
   did when the runtime was one classic script. scripts/build-esm.mjs appends this bridge
   to each of those modules; it re-exposes the module's own top-level bindings on
   globalThis only when the harness sets globalThis.__FIT_TEST_MODE__ (never in
   production). Mutable bindings (let/var/function) get setters, so a stub assigned in a
   test replaces the binding every importer sees (ES imports are live bindings);
   const/class bindings are read-only. */
import ts from 'typescript';

export function testBridge(source, fileName = 'module.js'){
  const file = ts.createSourceFile(fileName, source, ts.ScriptTarget.ES2022, false, ts.ScriptKind.JS);
  const names = new Map();
  const add = (name, mutable) => { if(name && !names.has(name)) names.set(name, mutable); };
  const bindingNames = node => {
    if(ts.isIdentifier(node)) return [node.text];
    return node.elements.flatMap(el => ts.isOmittedExpression(el) ? [] : bindingNames(el.name));
  };
  for(const stmt of file.statements){
    if(ts.isFunctionDeclaration(stmt) && stmt.name) add(stmt.name.text, true);
    else if(ts.isClassDeclaration(stmt) && stmt.name) add(stmt.name.text, false);
    else if(ts.isVariableStatement(stmt)){
      const mutable = !(stmt.declarationList.flags & ts.NodeFlags.Const);
      for(const decl of stmt.declarationList.declarations) for(const name of bindingNames(decl.name)) add(name, mutable);
    }
  }
  if(!names.size) return '';
  const lines = [...names].map(([name, mutable]) => mutable
    ? `  __fitExpose(${JSON.stringify(name)}, () => ${name}, value => { ${name} = value; });`
    : `  __fitExpose(${JSON.stringify(name)}, () => ${name});`);
  return `
/* Generated by scripts/test-bridge.mjs — test-only binding bridge, inert in production. */
if(globalThis.__FIT_TEST_MODE__ === true){
  const __fitExpose = (name, get, set) => {
    const current = Object.getOwnPropertyDescriptor(globalThis, name);
    if(current && !current.configurable) return;
    Object.defineProperty(globalThis, name, set ? {configurable:true, get, set} : {configurable:true, get});
  };
${lines.join('\n')}
}
`;
}

/* Modules that receive the bridge. */
export const TEST_BRIDGE_FILTER = /[\\/]src[\\/](app[\\/](\d\d-[\w-]+|options)|i18n[\\/]index)\.js$/;
