-- FetUre domain and demo taxonomy. Apply ONLY in a dedicated FetUre Supabase project.
-- Never seed fake user identities from the HTML concept.
create table if not exists public.feture_categories(id text primary key,title text not null,short_title text not null,icon text not null,accent_color text not null,position integer not null unique);
create table if not exists public.feture_interests(id text primary key,category_id text not null references public.feture_categories(id),title text not null,position integer not null,unique(category_id,position));
create table if not exists public.feture_tests(id text primary key,title text not null,description text not null,category_id text references public.feture_categories(id),question_count int not null check(question_count between 1 and 100));
create table if not exists public.feture_profiles(user_id uuid primary key references auth.users(id) on delete cascade,display_name text not null default '',about text not null default '',dating_enabled boolean not null default false,created_at timestamptz not null default now());
create table if not exists public.feture_interest_states(user_id uuid not null references auth.users(id) on delete cascade,interest_id text not null references public.feture_interests(id),status text not null check(status in ('unknown','curious','fantasy','want_to_try','experienced','soft_limit','hard_limit','not_interested')),intensity smallint check(intensity between 0 and 100),visibility text not null default 'private' check(visibility in ('private','public','granted')),updated_at timestamptz not null default now(),primary key(user_id,interest_id));
create table if not exists public.feture_test_responses(user_id uuid not null references auth.users(id) on delete cascade,test_id text not null references public.feture_tests(id),answers jsonb not null default '{}'::jsonb,taken_at timestamptz not null default now(),primary key(user_id,test_id));
create table if not exists public.feture_posts(id uuid primary key default gen_random_uuid(),author_id uuid not null references auth.users(id) on delete cascade,body text not null check(char_length(body)<=10000),audience text not null default 'private' check(audience in ('private','public','granted')),created_at timestamptz not null default now());
create table if not exists public.feture_profile_access(owner_id uuid not null references auth.users(id) on delete cascade,viewer_id uuid not null references auth.users(id) on delete cascade,scope text[] not null default '{}',expires_at timestamptz,revoked_at timestamptz,primary key(owner_id,viewer_id),check(owner_id<>viewer_id));
create table if not exists public.feture_dating_preferences(user_id uuid primary key references auth.users(id) on delete cascade,enabled boolean not null default false,preferences jsonb not null default '{}'::jsonb);
alter table public.feture_categories enable row level security;
alter table public.feture_interests enable row level security;
alter table public.feture_tests enable row level security;
alter table public.feture_profiles enable row level security;
alter table public.feture_interest_states enable row level security;
alter table public.feture_test_responses enable row level security;
alter table public.feture_posts enable row level security;
alter table public.feture_profile_access enable row level security;
alter table public.feture_dating_preferences enable row level security;
grant select on public.feture_categories,public.feture_interests,public.feture_tests to anon,authenticated;
grant select,insert,update,delete on public.feture_profiles,public.feture_interest_states,public.feture_test_responses,public.feture_posts,public.feture_profile_access,public.feture_dating_preferences to authenticated;
create policy "catalog_read_categories" on public.feture_categories for select to anon,authenticated using(true);
create policy "catalog_read_interests" on public.feture_interests for select to anon,authenticated using(true);
create policy "catalog_read_tests" on public.feture_tests for select to anon,authenticated using(true);
create policy "profiles_owner_select" on public.feture_profiles for select to authenticated using(((select auth.uid())=user_id));
create policy "profiles_owner_insert" on public.feture_profiles for insert to authenticated with check(((select auth.uid())=user_id));
create policy "profiles_owner_update" on public.feture_profiles for update to authenticated using(((select auth.uid())=user_id)) with check(((select auth.uid())=user_id));
create policy "profiles_owner_delete" on public.feture_profiles for delete to authenticated using(((select auth.uid())=user_id));
create policy "interest_states_owner_select" on public.feture_interest_states for select to authenticated using(((select auth.uid())=user_id));
create policy "interest_states_owner_insert" on public.feture_interest_states for insert to authenticated with check(((select auth.uid())=user_id));
create policy "interest_states_owner_update" on public.feture_interest_states for update to authenticated using(((select auth.uid())=user_id)) with check(((select auth.uid())=user_id));
create policy "interest_states_owner_delete" on public.feture_interest_states for delete to authenticated using(((select auth.uid())=user_id));
create policy "test_responses_owner_select" on public.feture_test_responses for select to authenticated using(((select auth.uid())=user_id));
create policy "test_responses_owner_insert" on public.feture_test_responses for insert to authenticated with check(((select auth.uid())=user_id));
create policy "test_responses_owner_update" on public.feture_test_responses for update to authenticated using(((select auth.uid())=user_id)) with check(((select auth.uid())=user_id));
create policy "test_responses_owner_delete" on public.feture_test_responses for delete to authenticated using(((select auth.uid())=user_id));
create policy "posts_owner_select" on public.feture_posts for select to authenticated using(((select auth.uid())=author_id));
create policy "posts_owner_insert" on public.feture_posts for insert to authenticated with check(((select auth.uid())=author_id));
create policy "posts_owner_update" on public.feture_posts for update to authenticated using(((select auth.uid())=author_id)) with check(((select auth.uid())=author_id));
create policy "posts_owner_delete" on public.feture_posts for delete to authenticated using(((select auth.uid())=author_id));
create policy "dating_preferences_owner_select" on public.feture_dating_preferences for select to authenticated using(((select auth.uid())=user_id));
create policy "dating_preferences_owner_insert" on public.feture_dating_preferences for insert to authenticated with check(((select auth.uid())=user_id));
create policy "dating_preferences_owner_update" on public.feture_dating_preferences for update to authenticated using(((select auth.uid())=user_id)) with check(((select auth.uid())=user_id));
create policy "dating_preferences_owner_delete" on public.feture_dating_preferences for delete to authenticated using(((select auth.uid())=user_id));
create policy "profile_access_owner_select" on public.feture_profile_access for select to authenticated using(((select auth.uid())=owner_id));
create policy "profile_access_owner_insert" on public.feture_profile_access for insert to authenticated with check(((select auth.uid())=owner_id));
create policy "profile_access_owner_update" on public.feture_profile_access for update to authenticated using(((select auth.uid())=owner_id)) with check(((select auth.uid())=owner_id));
create policy "profile_access_owner_delete" on public.feture_profile_access for delete to authenticated using(((select auth.uid())=owner_id));
insert into public.feture_categories values('category-1','Роли и динамика','Роли','layers','#7156cb',0) on conflict do nothing;
insert into public.feture_interests values('interest-1-1','category-1','Ведущая роль',0) on conflict do nothing;
insert into public.feture_interests values('interest-1-2','category-1','Принимающая роль',1) on conflict do nothing;
insert into public.feture_interests values('interest-1-3','category-1','Свитч',2) on conflict do nothing;
insert into public.feture_interests values('interest-1-4','category-1','Передача инициативы',3) on conflict do nothing;
insert into public.feture_interests values('interest-1-5','category-1','Контроль',4) on conflict do nothing;
insert into public.feture_interests values('interest-1-6','category-1','Доверие',5) on conflict do nothing;
insert into public.feture_interests values('interest-1-7','category-1','Партнёрская динамика',6) on conflict do nothing;
insert into public.feture_interests values('interest-1-8','category-1','Ролевой обмен',7) on conflict do nothing;
insert into public.feture_interests values('interest-1-9','category-1','Сервис',8) on conflict do nothing;
insert into public.feture_interests values('interest-1-10','category-1','Наставничество',9) on conflict do nothing;
insert into public.feture_interests values('interest-1-11','category-1','Равноправие',10) on conflict do nothing;
insert into public.feture_interests values('interest-1-12','category-1','Договорённости',11) on conflict do nothing;
insert into public.feture_categories values('category-2','Близость и контакт','Близость','heart','#e35278',1) on conflict do nothing;
insert into public.feture_interests values('interest-2-1','category-2','Телесная близость',0) on conflict do nothing;
insert into public.feture_interests values('interest-2-2','category-2','Объятия',1) on conflict do nothing;
insert into public.feture_interests values('interest-2-3','category-2','Нежность',2) on conflict do nothing;
insert into public.feture_interests values('interest-2-4','category-2','Поцелуи',3) on conflict do nothing;
insert into public.feture_interests values('interest-2-5','category-2','Массаж',4) on conflict do nothing;
insert into public.feture_interests values('interest-2-6','category-2','Медленный темп',5) on conflict do nothing;
insert into public.feture_interests values('interest-2-7','category-2','Совместный отдых',6) on conflict do nothing;
insert into public.feture_interests values('interest-2-8','category-2','Тактильность',7) on conflict do nothing;
insert into public.feture_interests values('interest-2-9','category-2','Зрительный контакт',8) on conflict do nothing;
insert into public.feture_interests values('interest-2-10','category-2','Сенсорное внимание',9) on conflict do nothing;
insert into public.feture_interests values('interest-2-11','category-2','Игра с дистанцией',10) on conflict do nothing;
insert into public.feture_interests values('interest-2-12','category-2','Послеобсуждение',11) on conflict do nothing;
insert into public.feture_categories values('category-3','Сенсорика и ощущения','Ощущения','spark','#bf765b',2) on conflict do nothing;
insert into public.feture_interests values('interest-3-1','category-3','Мягкие текстуры',0) on conflict do nothing;
insert into public.feture_interests values('interest-3-2','category-3','Шёлк',1) on conflict do nothing;
insert into public.feture_interests values('interest-3-3','category-3','Кожа',2) on conflict do nothing;
insert into public.feture_interests values('interest-3-4','category-3','Температура',3) on conflict do nothing;
insert into public.feture_interests values('interest-3-5','category-3','Ароматы',4) on conflict do nothing;
insert into public.feture_interests values('interest-3-6','category-3','Звуки',5) on conflict do nothing;
insert into public.feture_interests values('interest-3-7','category-3','Тишина',6) on conflict do nothing;
insert into public.feture_interests values('interest-3-8','category-3','Прикосновения',7) on conflict do nothing;
insert into public.feture_interests values('interest-3-9','category-3','Контраст ощущений',8) on conflict do nothing;
insert into public.feture_interests values('interest-3-10','category-3','Повязка на глаза',9) on conflict do nothing;
insert into public.feture_interests values('interest-3-11','category-3','Свет и тень',10) on conflict do nothing;
insert into public.feture_interests values('interest-3-12','category-3','Сенсорные ритуалы',11) on conflict do nothing;
insert into public.feture_categories values('category-4','Романтика и эмоции','Эмоции','heart','#aa5f93',3) on conflict do nothing;
insert into public.feture_interests values('interest-4-1','category-4','Забота',0) on conflict do nothing;
insert into public.feture_interests values('interest-4-2','category-4','Открытость',1) on conflict do nothing;
insert into public.feture_interests values('interest-4-3','category-4','Комплименты',2) on conflict do nothing;
insert into public.feture_interests values('interest-4-4','category-4','Романтика',3) on conflict do nothing;
insert into public.feture_interests values('interest-4-5','category-4','Поддержка',4) on conflict do nothing;
insert into public.feture_interests values('interest-4-6','category-4','Внимательность',5) on conflict do nothing;
insert into public.feture_interests values('interest-4-7','category-4','Публичное проявление чувств',6) on conflict do nothing;
insert into public.feture_interests values('interest-4-8','category-4','Интеллектуальная связь',7) on conflict do nothing;
insert into public.feture_interests values('interest-4-9','category-4','Уязвимость',8) on conflict do nothing;
insert into public.feture_interests values('interest-4-10','category-4','Нежная инициатива',9) on conflict do nothing;
insert into public.feture_interests values('interest-4-11','category-4','Письма',10) on conflict do nothing;
insert into public.feture_interests values('interest-4-12','category-4','Эмоциональная безопасность',11) on conflict do nothing;
insert into public.feture_categories values('category-5','Фантазии и сценарии','Фантазии','sparkle','#7563ce',4) on conflict do nothing;
insert into public.feture_interests values('interest-5-1','category-5','Ролевые сценарии',0) on conflict do nothing;
insert into public.feture_interests values('interest-5-2','category-5','Театральность',1) on conflict do nothing;
insert into public.feture_interests values('interest-5-3','category-5','Костюмы',2) on conflict do nothing;
insert into public.feture_interests values('interest-5-4','category-5','Воображаемые сюжеты',3) on conflict do nothing;
insert into public.feture_interests values('interest-5-5','category-5','Смена контекста',4) on conflict do nothing;
insert into public.feture_interests values('interest-5-6','category-5','Игра образов',5) on conflict do nothing;
insert into public.feture_interests values('interest-5-7','category-5','Спонтанность',6) on conflict do nothing;
insert into public.feture_interests values('interest-5-8','category-5','Планирование',7) on conflict do nothing;
insert into public.feture_interests values('interest-5-9','category-5','Фантазии в переписке',8) on conflict do nothing;
insert into public.feture_interests values('interest-5-10','category-5','Эксперименты',9) on conflict do nothing;
insert into public.feture_interests values('interest-5-11','category-5','Импровизация',10) on conflict do nothing;
insert into public.feture_interests values('interest-5-12','category-5','Фантазия без реализации',11) on conflict do nothing;
insert into public.feture_categories values('category-6','Эстетика и стиль','Эстетика','eye','#b16c8b',5) on conflict do nothing;
insert into public.feture_interests values('interest-6-1','category-6','Фотография',0) on conflict do nothing;
insert into public.feture_interests values('interest-6-2','category-6','Стиль одежды',1) on conflict do nothing;
insert into public.feture_interests values('interest-6-3','category-6','Латекс',2) on conflict do nothing;
insert into public.feture_interests values('interest-6-4','category-6','Кружево',3) on conflict do nothing;
insert into public.feture_interests values('interest-6-5','category-6','Минимализм',4) on conflict do nothing;
insert into public.feture_interests values('interest-6-6','category-6','Готика',5) on conflict do nothing;
insert into public.feture_interests values('interest-6-7','category-6','Украшения',6) on conflict do nothing;
insert into public.feture_interests values('interest-6-8','category-6','Маски',7) on conflict do nothing;
insert into public.feture_interests values('interest-6-9','category-6','Макияж',8) on conflict do nothing;
insert into public.feture_interests values('interest-6-10','category-6','Перформанс',9) on conflict do nothing;
insert into public.feture_interests values('interest-6-11','category-6','Портреты',10) on conflict do nothing;
insert into public.feture_interests values('interest-6-12','category-6','Визуальные образы',11) on conflict do nothing;
insert into public.feture_categories values('category-7','Практики и исследования','Практики','compass','#278e84',6) on conflict do nothing;
insert into public.feture_interests values('interest-7-1','category-7','Шибари',0) on conflict do nothing;
insert into public.feture_interests values('interest-7-2','category-7','Связывание',1) on conflict do nothing;
insert into public.feture_interests values('interest-7-3','category-7','Ролевые игры',2) on conflict do nothing;
insert into public.feture_interests values('interest-7-4','category-7','Договорённости',3) on conflict do nothing;
insert into public.feture_interests values('interest-7-5','category-7','Совместное изучение',4) on conflict do nothing;
insert into public.feture_interests values('interest-7-6','category-7','Обучающие встречи',5) on conflict do nothing;
insert into public.feture_interests values('interest-7-7','category-7','Мягкие эксперименты',6) on conflict do nothing;
insert into public.feture_interests values('interest-7-8','category-7','Партнёрские ритуалы',7) on conflict do nothing;
insert into public.feture_interests values('interest-7-9','category-7','Сенсорные упражнения',8) on conflict do nothing;
insert into public.feture_interests values('interest-7-10','category-7','Безопасные практики',9) on conflict do nothing;
insert into public.feture_interests values('interest-7-11','category-7','Обмен опытом',10) on conflict do nothing;
insert into public.feture_interests values('interest-7-12','category-7','Осознанность',11) on conflict do nothing;
insert into public.feture_categories values('category-8','Форматы отношений','Отношения','users','#c1774f',7) on conflict do nothing;
insert into public.feture_interests values('interest-8-1','category-8','Моногамия',0) on conflict do nothing;
insert into public.feture_interests values('interest-8-2','category-8','Открытые отношения',1) on conflict do nothing;
insert into public.feture_interests values('interest-8-3','category-8','Полиамория',2) on conflict do nothing;
insert into public.feture_interests values('interest-8-4','category-8','Свинг',3) on conflict do nothing;
insert into public.feture_interests values('interest-8-5','category-8','Анархия отношений',4) on conflict do nothing;
insert into public.feture_interests values('interest-8-6','category-8','Партнёрство без романтики',5) on conflict do nothing;
insert into public.feture_interests values('interest-8-7','category-8','Дружба',6) on conflict do nothing;
insert into public.feture_interests values('interest-8-8','category-8','Долгосрочная связь',7) on conflict do nothing;
insert into public.feture_interests values('interest-8-9','category-8','Неформальные отношения',8) on conflict do nothing;
insert into public.feture_interests values('interest-8-10','category-8','Профиль пары',9) on conflict do nothing;
insert into public.feture_interests values('interest-8-11','category-8','Совместное общение',10) on conflict do nothing;
insert into public.feture_interests values('interest-8-12','category-8','Личная автономия',11) on conflict do nothing;
insert into public.feture_categories values('category-9','Общение и социальность','Общение','chat','#597fba',8) on conflict do nothing;
insert into public.feture_interests values('interest-9-1','category-9','Личные сообщения',0) on conflict do nothing;
insert into public.feture_interests values('interest-9-2','category-9','Групповые обсуждения',1) on conflict do nothing;
insert into public.feture_interests values('interest-9-3','category-9','Камерные встречи',2) on conflict do nothing;
insert into public.feture_interests values('interest-9-4','category-9','Вечеринки',3) on conflict do nothing;
insert into public.feture_interests values('interest-9-5','category-9','Мастер-классы',4) on conflict do nothing;
insert into public.feture_interests values('interest-9-6','category-9','События',5) on conflict do nothing;
insert into public.feture_interests values('interest-9-7','category-9','Онлайн-знакомства',6) on conflict do nothing;
insert into public.feture_interests values('interest-9-8','category-9','Новые друзья',7) on conflict do nothing;
insert into public.feture_interests values('interest-9-9','category-9','Большие сообщества',8) on conflict do nothing;
insert into public.feture_interests values('interest-9-10','category-9','Анонимные вопросы',9) on conflict do nothing;
insert into public.feture_interests values('interest-9-11','category-9','Обмен историями',10) on conflict do nothing;
insert into public.feture_interests values('interest-9-12','category-9','Тематические клубы',11) on conflict do nothing;
insert into public.feture_categories values('category-10','Границы и безопасность','Границы','shield','#258d71',9) on conflict do nothing;
insert into public.feture_interests values('interest-10-1','category-10','Согласие',0) on conflict do nothing;
insert into public.feture_interests values('interest-10-2','category-10','Стоп-слово',1) on conflict do nothing;
insert into public.feture_interests values('interest-10-3','category-10','Чёткие границы',2) on conflict do nothing;
insert into public.feture_interests values('interest-10-4','category-10','Мягкие границы',3) on conflict do nothing;
insert into public.feture_interests values('interest-10-5','category-10','Приватность',4) on conflict do nothing;
insert into public.feture_interests values('interest-10-6','category-10','Конфиденциальность',5) on conflict do nothing;
insert into public.feture_interests values('interest-10-7','category-10','Aftercare',6) on conflict do nothing;
insert into public.feture_interests values('interest-10-8','category-10','Обсуждение ожиданий',7) on conflict do nothing;
insert into public.feture_interests values('interest-10-9','category-10','Проверка самочувствия',8) on conflict do nothing;
insert into public.feture_interests values('interest-10-10','category-10','Личные правила',9) on conflict do nothing;
insert into public.feture_interests values('interest-10-11','category-10','Право передумать',10) on conflict do nothing;
insert into public.feture_interests values('interest-10-12','category-10','Безопасность встреч',11) on conflict do nothing;
insert into public.feture_categories values('category-11','Самовыражение и идентичность','Идентичность','user','#ab648a',10) on conflict do nothing;
insert into public.feture_interests values('interest-11-1','category-11','Самовыражение',0) on conflict do nothing;
insert into public.feture_interests values('interest-11-2','category-11','Самоопределение',1) on conflict do nothing;
insert into public.feture_interests values('interest-11-3','category-11','Ориентация',2) on conflict do nothing;
insert into public.feture_interests values('interest-11-4','category-11','Гендерная идентичность',3) on conflict do nothing;
insert into public.feture_interests values('interest-11-5','category-11','Местоимения',4) on conflict do nothing;
insert into public.feture_interests values('interest-11-6','category-11','Личный стиль',5) on conflict do nothing;
insert into public.feture_interests values('interest-11-7','category-11','Принятие себя',6) on conflict do nothing;
insert into public.feture_interests values('interest-11-8','category-11','Видимость',7) on conflict do nothing;
insert into public.feture_interests values('interest-11-9','category-11','Неоднозначность',8) on conflict do nothing;
insert into public.feture_interests values('interest-11-10','category-11','Любопытство',9) on conflict do nothing;
insert into public.feture_interests values('interest-11-11','category-11','Личные ценности',10) on conflict do nothing;
insert into public.feture_interests values('interest-11-12','category-11','Изменения со временем',11) on conflict do nothing;
insert into public.feture_categories values('category-12','Ритм и образ жизни','Образ жизни','clock','#a67637',11) on conflict do nothing;
insert into public.feture_interests values('interest-12-1','category-12','Спонтанность',0) on conflict do nothing;
insert into public.feture_interests values('interest-12-2','category-12','Планирование встреч',1) on conflict do nothing;
insert into public.feture_interests values('interest-12-3','category-12','Уединение',2) on conflict do nothing;
insert into public.feture_interests values('interest-12-4','category-12','Общительность',3) on conflict do nothing;
insert into public.feture_interests values('interest-12-5','category-12','Путешествия',4) on conflict do nothing;
insert into public.feture_interests values('interest-12-6','category-12','Медленное знакомство',5) on conflict do nothing;
insert into public.feture_interests values('interest-12-7','category-12','Активный отдых',6) on conflict do nothing;
insert into public.feture_interests values('interest-12-8','category-12','Домашний уют',7) on conflict do nothing;
insert into public.feture_interests values('interest-12-9','category-12','Городские события',8) on conflict do nothing;
insert into public.feture_interests values('interest-12-10','category-12','Баланс времени',9) on conflict do nothing;
insert into public.feture_interests values('interest-12-11','category-12','Свободный график',10) on conflict do nothing;
insert into public.feture_interests values('interest-12-12','category-12','Уютные пространства',11) on conflict do nothing;
insert into public.feture_tests values('test-1','Твои роли и динамика','Как тебе комфортнее распределять инициативу','category-1',8) on conflict do nothing;
insert into public.feture_tests values('test-2','Язык близости','Что создаёт ощущение контакта','category-2',8) on conflict do nothing;
insert into public.feture_tests values('test-3','Карта ощущений','Какие ощущения интересны тебе','category-3',8) on conflict do nothing;
insert into public.feture_tests values('test-4','Эмоциональная связь','Как проявляются доверие и забота','category-4',8) on conflict do nothing;
insert into public.feture_tests values('test-5','Фантазия или опыт','Чего хочется только в воображении','category-5',8) on conflict do nothing;
insert into public.feture_tests values('test-6','Эстетика и самовыражение','Как образы отражают твои желания','category-6',8) on conflict do nothing;
insert into public.feture_tests values('test-7','Исследовать новое','Про любопытство и темп','category-7',8) on conflict do nothing;
insert into public.feture_tests values('test-8','Формат отношений','Комфортные договорённости с партнёром','category-8',8) on conflict do nothing;
insert into public.feture_tests values('test-9','Социальная энергия','Общение, группы и встречи','category-9',8) on conflict do nothing;
insert into public.feture_tests values('test-10','Твои границы','Что обязательно учитывать другим','category-10',8) on conflict do nothing;
insert into public.feture_tests values('test-11','Быть собой','Что важно для идентичности','category-11',8) on conflict do nothing;
insert into public.feture_tests values('test-12','Твой ритм','Как ты любишь развивать близость','category-12',8) on conflict do nothing;
insert into public.feture_tests values('test-13','Сила доверия','Доверие, правила и открытость','category-10',8) on conflict do nothing;
insert into public.feture_tests values('test-14','Комфорт в сообществе','Где тебе легко быть собой','category-9',8) on conflict do nothing;
insert into public.feture_tests values('test-15','Новое без давления','Твой темп открытий','category-7',8) on conflict do nothing;
insert into public.feture_tests values('test-16','Моя приватность','Что и кому комфортно показывать','category-10',8) on conflict do nothing;
insert into public.feture_tests values('test-17','Способы заботиться','Поддержка и бережность','category-4',8) on conflict do nothing;
insert into public.feture_tests values('test-18','Общий язык','Как обсуждать ожидания','category-8',8) on conflict do nothing;
