import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

const root = process.cwd();
const out = path.join(root, 'dist');
const files = [
  'index.html',
  'style.css',
  'app.js',
  'manifest.webmanifest',
  'sw.js',
  'icon-192.png',
  'icon-512.png',
  'icon-512-maskable.png',
  'mobile.js'
];

function cleanOrigin(value, fallback){
  const raw = (value || fallback).trim().replace(/\/$/, '');
  const url = new URL(raw);
  if(url.protocol !== 'https:') throw new Error(`URL must use https: ${raw}`);
  return url.origin + (url.pathname === '/' ? '' : url.pathname);
}

const apiBase = cleanOrigin(process.env.FIT_TIMER_API_URL, 'https://fittimer99.vercel.app');
const publicAppUrl = cleanOrigin(process.env.FIT_TIMER_PUBLIC_URL, apiBase) + '/';

await rm(out, {recursive:true, force:true});
await mkdir(out, {recursive:true});
await Promise.all(files.map(file => cp(path.join(root, file), path.join(out, file))));

const config = `/* Generated by scripts/build-web.mjs. Do not edit dist directly. */\nwindow.FIT_TIMER_CONFIG = Object.freeze(${JSON.stringify({apiBase, publicAppUrl}, null, 2)});\n`;
await writeFile(path.join(out, 'app.config.js'), config, 'utf8');

const html = await readFile(path.join(out, 'index.html'), 'utf8');
if(!html.includes('app.config.js') || !html.includes('mobile.js') || !html.includes('app.js') || !html.includes('style.css')){
  throw new Error('index.html must load runtime scripts and stylesheet');
}

console.log(`Built ${files.length + 1} files in dist`);
console.log(`API: ${apiBase}`);
console.log(`Public links: ${publicAppUrl}`);
