import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

const root = process.cwd();
const out = path.join(root, 'dist');
const files = [
  'index.html',
  'style.css',
  'app.js',
  'mobile.js'
];

function cleanOrigin(value, fallback){
  const raw = String(value || fallback || '').trim().replace(/\/$/, '');
  const url = new URL(raw);
  if(url.protocol !== 'https:') throw new Error(`URL must use https: ${raw}`);
  return url.origin + (url.pathname === '/' ? '' : url.pathname);
}

const product = JSON.parse(await readFile(path.join(root, 'config/product.json'), 'utf8'));
const apiBase = cleanOrigin(process.env.FIT_TIMER_API_URL, product.defaultApiUrl);
const publicAppUrl = cleanOrigin(process.env.FIT_TIMER_PUBLIC_URL, product.defaultPublicUrl || apiBase) + '/';

await rm(out, {recursive:true, force:true});
await mkdir(out, {recursive:true});
await Promise.all(files.map(file => cp(path.join(root, file), path.join(out, file))));

const runtimeConfig = {
  appId: product.id,
  appName: product.name,
  slug: product.slug,
  brand: product.brand,
  features: product.features,
  apiBase,
  publicAppUrl
};
const config = `/* Generated by scripts/build-web.mjs. Do not edit dist directly. */\nwindow.FIT_TIMER_CONFIG = Object.freeze(${JSON.stringify(runtimeConfig, null, 2)});\n`;
await writeFile(path.join(out, 'app.config.js'), config, 'utf8');

const html = await readFile(path.join(out, 'index.html'), 'utf8');
if(!html.includes('app.config.js') || !html.includes('mobile.js') || !html.includes('app.js') || !html.includes('style.css')){
  throw new Error('index.html must load runtime scripts and stylesheet');
}

console.log(`Built ${files.length + 1} files in dist`);
console.log(`App: ${product.name} (${product.id})`);
console.log(`API: ${apiBase}`);
console.log(`Public links: ${publicAppUrl}`);
